Added online help option

diff --git a/qlsh b/qlsh
--- a/qlsh
+++ b/qlsh
@@ -7,7 +7,7 @@
 #
 # Run `qlsh` on its own for more help
 #
-# Requires codeql, bash, jq and (optionally) rlwrap to be installed
+# Requires codeql, bash, jq and (optionally) rlwrap and curl to be installed
 #
 # Copyright (C) 2024, GitHub
 
@@ -68,6 +68,39 @@ function codeql_shell_help {
     echo "  reset: clear the current query buffer (or use Ctrl-C)" >&2
 }
 
+function codeql_shell_help_lookup {
+    # lookup help in CodeQL docs for a specific command
+    # search details taken from https://codeql.github.com/codeql-standard-libraries/search.html
+    search="$(echo "$1" | jq --slurp --raw-input --raw-output @uri)"
+
+    codeql_search_cdn_url="https://s7.searchcdn.com/93b4d287e2fc079a4089412b669785d5/${search}/0/1166/?s=1713199271142&categories=2x${_language}&resultCount=10"
+
+    if command -v curl &> /dev/null; then
+        result_url=$(curl -s "${codeql_search_cdn_url}" | \
+        # remove 'addsearch.searchResults(' prefix and ');' suffix
+        sed 's/^addsearch.searchResults(//;s/);$//' | \
+        # extract the first result
+        jq '.es.hits.hits[0].fields.url' | \
+        # remove quotes around URL
+        sed 's/"//g')
+
+        if [[ -z "${result_url}" ]]; then
+            echo "[-] No online help found for ${1}" >&2
+            return
+        fi
+
+        # open with text browser if available
+        if command -v lynx &> /dev/null; then
+            lynx -dump "${result_url}"
+        else
+            echo "Online help: ${result_url}"
+        fi
+
+    else
+        echo "[-] curl not found, cannot give online help" >&2
+    fi
+}
+
 function codeql_shell_prompt {
     echo -n "${_codeql_shell_prompt}"
 }
@@ -115,6 +148,14 @@ function codeql_shell_repl {
 
         if [[ "${line}" == "help" ]]; then
             codeql_shell_help
+            codeql_shell_prompt
+            continue
+        fi
+
+        codeql_shell_regex_help="^help "
+
+        if [[ "${line}" =~ $codeql_shell_regex_help ]]; then
+            codeql_shell_help_lookup "$(echo "${line}" | cut -d " " -f2)"
             codeql_shell_prompt
             continue
         fi
@@ -210,6 +251,7 @@ function main {
     export -f codeql_shell_prompt
     export -f codeql_shell_cleanup
     export -f codeql_shell_help
+    export -f codeql_shell_help_lookup
     export -f codeql_shell_quit
     export -f codeql_shell_trunc
 
